# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d928824a839a3e60cc06d1e200e3b7b5fc89ec001a21df6cc3ee019df929addaf9d08697d840eb65d226ac8748f297c47da8ae69d03ed9f94060dc8d2a7ca8

test:
  secret_key_base: 08758adf39531cb47ad20e8d9d05887040cfdeb0ccf897e173ba45592352633cd83609a6371d4fb478842effab6dc26e4a616f38ec642d7e22bf09f0e6d42a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
